// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/v1/link.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _link_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Link with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Link) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Link with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LinkMultiError, or nil if none found.
func (m *Link) ValidateAll() error {
	return m.validate(true)
}

func (m *Link) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for FullUri

	// no validation rules for ShortUri

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LinkValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LinkValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LinkValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LinkValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LinkValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LinkValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LinkMultiError(errors)
	}

	return nil
}

// LinkMultiError is an error wrapping multiple validation errors returned by
// Link.ValidateAll() if the designated constraints aren't met.
type LinkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LinkMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LinkMultiError) AllErrors() []error { return m }

// LinkValidationError is the validation error returned by Link.Validate if the
// designated constraints aren't met.
type LinkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LinkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LinkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LinkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LinkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LinkValidationError) ErrorName() string { return "LinkValidationError" }

// Error satisfies the builtin error interface
func (e LinkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLink.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LinkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LinkValidationError{}

// Validate checks the field values on CreateLinkRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateLinkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateLinkRequestMultiError, or nil if none found.
func (m *CreateLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if uri, err := url.Parse(m.GetFullUri()); err != nil {
		err = CreateLinkRequestValidationError{
			field:  "FullUri",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := CreateLinkRequestValidationError{
			field:  "FullUri",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.ExpiresAt != nil {

		if m.GetExpiresAt() == nil {
			err := CreateLinkRequestValidationError{
				field:  "ExpiresAt",
				reason: "value is required",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return CreateLinkRequestMultiError(errors)
	}

	return nil
}

// CreateLinkRequestMultiError is an error wrapping multiple validation errors
// returned by CreateLinkRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateLinkRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateLinkRequestMultiError) AllErrors() []error { return m }

// CreateLinkRequestValidationError is the validation error returned by
// CreateLinkRequest.Validate if the designated constraints aren't met.
type CreateLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateLinkRequestValidationError) ErrorName() string {
	return "CreateLinkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateLinkRequestValidationError{}

// Validate checks the field values on GetLinkRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLinkRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetLinkRequestMultiError,
// or nil if none found.
func (m *GetLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = GetLinkRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetLinkRequestMultiError(errors)
	}

	return nil
}

func (m *GetLinkRequest) _validateUuid(uuid string) error {
	if matched := _link_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetLinkRequestMultiError is an error wrapping multiple validation errors
// returned by GetLinkRequest.ValidateAll() if the designated constraints
// aren't met.
type GetLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLinkRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLinkRequestMultiError) AllErrors() []error { return m }

// GetLinkRequestValidationError is the validation error returned by
// GetLinkRequest.Validate if the designated constraints aren't met.
type GetLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLinkRequestValidationError) ErrorName() string { return "GetLinkRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLinkRequestValidationError{}

// Validate checks the field values on DeleteLinkRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteLinkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteLinkRequestMultiError, or nil if none found.
func (m *DeleteLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = DeleteLinkRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteLinkRequestMultiError(errors)
	}

	return nil
}

func (m *DeleteLinkRequest) _validateUuid(uuid string) error {
	if matched := _link_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// DeleteLinkRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteLinkRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteLinkRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteLinkRequestMultiError) AllErrors() []error { return m }

// DeleteLinkRequestValidationError is the validation error returned by
// DeleteLinkRequest.Validate if the designated constraints aren't met.
type DeleteLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteLinkRequestValidationError) ErrorName() string {
	return "DeleteLinkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteLinkRequestValidationError{}

// Validate checks the field values on PatchLinkRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PatchLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PatchLinkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PatchLinkRequestMultiError, or nil if none found.
func (m *PatchLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PatchLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = PatchLinkRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetNewExpiresAt() == nil {
		err := PatchLinkRequestValidationError{
			field:  "NewExpiresAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PatchLinkRequestMultiError(errors)
	}

	return nil
}

func (m *PatchLinkRequest) _validateUuid(uuid string) error {
	if matched := _link_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PatchLinkRequestMultiError is an error wrapping multiple validation errors
// returned by PatchLinkRequest.ValidateAll() if the designated constraints
// aren't met.
type PatchLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PatchLinkRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PatchLinkRequestMultiError) AllErrors() []error { return m }

// PatchLinkRequestValidationError is the validation error returned by
// PatchLinkRequest.Validate if the designated constraints aren't met.
type PatchLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PatchLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PatchLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PatchLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PatchLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PatchLinkRequestValidationError) ErrorName() string { return "PatchLinkRequestValidationError" }

// Error satisfies the builtin error interface
func (e PatchLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPatchLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PatchLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PatchLinkRequestValidationError{}

// Validate checks the field values on PatchLinkResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PatchLinkResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PatchLinkResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PatchLinkResponseMultiError, or nil if none found.
func (m *PatchLinkResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PatchLinkResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsSuccessfully

	if len(errors) > 0 {
		return PatchLinkResponseMultiError(errors)
	}

	return nil
}

// PatchLinkResponseMultiError is an error wrapping multiple validation errors
// returned by PatchLinkResponse.ValidateAll() if the designated constraints
// aren't met.
type PatchLinkResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PatchLinkResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PatchLinkResponseMultiError) AllErrors() []error { return m }

// PatchLinkResponseValidationError is the validation error returned by
// PatchLinkResponse.Validate if the designated constraints aren't met.
type PatchLinkResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PatchLinkResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PatchLinkResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PatchLinkResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PatchLinkResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PatchLinkResponseValidationError) ErrorName() string {
	return "PatchLinkResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PatchLinkResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPatchLinkResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PatchLinkResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PatchLinkResponseValidationError{}

// Validate checks the field values on PutLinkRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PutLinkRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PutLinkRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PutLinkRequestMultiError,
// or nil if none found.
func (m *PutLinkRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PutLinkRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = PutLinkRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if uri, err := url.Parse(m.GetFullUri()); err != nil {
		err = PutLinkRequestValidationError{
			field:  "FullUri",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := PutLinkRequestValidationError{
			field:  "FullUri",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetNewExpiresAt() == nil {
		err := PutLinkRequestValidationError{
			field:  "NewExpiresAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PutLinkRequestMultiError(errors)
	}

	return nil
}

func (m *PutLinkRequest) _validateUuid(uuid string) error {
	if matched := _link_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PutLinkRequestMultiError is an error wrapping multiple validation errors
// returned by PutLinkRequest.ValidateAll() if the designated constraints
// aren't met.
type PutLinkRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PutLinkRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PutLinkRequestMultiError) AllErrors() []error { return m }

// PutLinkRequestValidationError is the validation error returned by
// PutLinkRequest.Validate if the designated constraints aren't met.
type PutLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PutLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PutLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PutLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PutLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PutLinkRequestValidationError) ErrorName() string { return "PutLinkRequestValidationError" }

// Error satisfies the builtin error interface
func (e PutLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPutLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PutLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PutLinkRequestValidationError{}

// Validate checks the field values on PutLinkResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PutLinkResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PutLinkResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PutLinkResponseMultiError, or nil if none found.
func (m *PutLinkResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PutLinkResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsSuccessfully

	if len(errors) > 0 {
		return PutLinkResponseMultiError(errors)
	}

	return nil
}

// PutLinkResponseMultiError is an error wrapping multiple validation errors
// returned by PutLinkResponse.ValidateAll() if the designated constraints
// aren't met.
type PutLinkResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PutLinkResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PutLinkResponseMultiError) AllErrors() []error { return m }

// PutLinkResponseValidationError is the validation error returned by
// PutLinkResponse.Validate if the designated constraints aren't met.
type PutLinkResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PutLinkResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PutLinkResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PutLinkResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PutLinkResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PutLinkResponseValidationError) ErrorName() string { return "PutLinkResponseValidationError" }

// Error satisfies the builtin error interface
func (e PutLinkResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPutLinkResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PutLinkResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PutLinkResponseValidationError{}
