// +template and .WithEntity .WithGRPC
syntax = "proto3";
package draftproject.api.v1;

option go_package = "gitlab.bronevik.space/bronevik/backend/draft-project/pkg/api/v1";

import "google/api/annotations.proto";
import "google/api/field_behavior.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

// Сервис для работы с MyItem
service DraftProjectService {
    // Создание нового элемента
    rpc CreateMyItem(CreateMyItemRequest) returns (MyItem) {
        option (google.api.http) = {// +template .WithHTTP
            post: "/api/v1/my-items"    // +template .WithHTTP
            body: "*"   // +template .WithHTTP
        };  // +template .WithHTTP
    };

    // Получение существующего элемента
    rpc GetMyItem(GetMyItemRequest) returns (MyItem) {
        option (google.api.http) = {// +template .WithHTTP
            get: "/api/v1/my-items/{id}"    // +template .WithHTTP
        };  // +template .WithHTTP
    };

    // Обновление существующего элемента
    rpc UpdateMyItem(UpdateMyItemRequest) returns (MyItem) {
        option (google.api.http) = {// +template .WithHTTP
            patch: "/api/v1/my-items/{id}"  // +template .WithHTTP
            body: "*"   // +template .WithHTTP
        };  // +template .WithHTTP
    };

    // Удаление существующего элемента
    rpc DeleteMyItem(DeleteMyItemRequest) returns (google.protobuf.Empty) {
        option (google.api.http) = {// +template .WithHTTP
            delete: "/api/v1/my-items/{id}"    // +template .WithHTTP
        };  // +template .WithHTTP
    };

    // Получение списка элементов
    rpc ListMyItems(ListMyItemsRequest) returns (ListMyItemsResponse) {
        option (google.api.http) = {// +template .WithHTTP
            get: "/api/v1/my-items" // +template .WithHTTP
        };  // +template .WithHTTP
    };
}

// Описание элемента
message MyItem {
    // уникальный идентификатор в формате UUID
    string id = 1;
    // имя элемента
    string name = 2;
    // время создания элемента
    google.protobuf.Timestamp created_at = 3;
    // время последнего изменения элемента
    google.protobuf.Timestamp updated_at = 4;
}

// Запрос на создание элемента
message CreateMyItemRequest {
    // имя элемента
    string name = 1;
}

// Запрос на получение элемента
message GetMyItemRequest {
    // уникальный идентификатор в формате UUID
    string id = 1;
}

// Запрос на обновление элемента
message UpdateMyItemRequest {
    // уникальный идентификатор в формате UUID
    string id = 1;
    // имя элемента
    string name = 2;
}

// Запрос на удаление элемента
message DeleteMyItemRequest {
    // уникальный идентификатор в формате UUID
    string id = 1;
}

// Запрос на получение списка элементов
message ListMyItemsRequest {
    // размер страницы
    int32 page_size = 1;
    // номер страницы
    int32 page_number = 2;
}

// Список элементов
message ListMyItemsResponse {
    // список элементов на странице
    repeated MyItem my_items = 1;
    // номер следующей страницы
    int32 next_page_number = 2;
}
