// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/v1/link.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LinkShortenerService_CreateLink_FullMethodName     = "/linkshortener.api.v1.LinkShortenerService/CreateLink"
	LinkShortenerService_GetLink_FullMethodName        = "/linkshortener.api.v1.LinkShortenerService/GetLink"
	LinkShortenerService_UpdateLink_FullMethodName     = "/linkshortener.api.v1.LinkShortenerService/UpdateLink"
	LinkShortenerService_ExtendLifeTime_FullMethodName = "/linkshortener.api.v1.LinkShortenerService/ExtendLifeTime"
	LinkShortenerService_DeleteMyItem_FullMethodName   = "/linkshortener.api.v1.LinkShortenerService/DeleteMyItem"
	LinkShortenerService_Redirect_FullMethodName       = "/linkshortener.api.v1.LinkShortenerService/Redirect"
)

// LinkShortenerServiceClient is the client API for LinkShortenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkShortenerServiceClient interface {
	CreateLink(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*Link, error)
	GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*Link, error)
	UpdateLink(ctx context.Context, in *PutLinkRequest, opts ...grpc.CallOption) (*PutLinkResponse, error)
	ExtendLifeTime(ctx context.Context, in *PatchLinkRequest, opts ...grpc.CallOption) (*PatchLinkResponse, error)
	DeleteMyItem(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error)
	Redirect(ctx context.Context, in *RedirectRequest, opts ...grpc.CallOption) (*RedirectResponse, error)
}

type linkShortenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkShortenerServiceClient(cc grpc.ClientConnInterface) LinkShortenerServiceClient {
	return &linkShortenerServiceClient{cc}
}

func (c *linkShortenerServiceClient) CreateLink(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*Link, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Link)
	err := c.cc.Invoke(ctx, LinkShortenerService_CreateLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkShortenerServiceClient) GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*Link, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Link)
	err := c.cc.Invoke(ctx, LinkShortenerService_GetLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkShortenerServiceClient) UpdateLink(ctx context.Context, in *PutLinkRequest, opts ...grpc.CallOption) (*PutLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutLinkResponse)
	err := c.cc.Invoke(ctx, LinkShortenerService_UpdateLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkShortenerServiceClient) ExtendLifeTime(ctx context.Context, in *PatchLinkRequest, opts ...grpc.CallOption) (*PatchLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchLinkResponse)
	err := c.cc.Invoke(ctx, LinkShortenerService_ExtendLifeTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkShortenerServiceClient) DeleteMyItem(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLinkResponse)
	err := c.cc.Invoke(ctx, LinkShortenerService_DeleteMyItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkShortenerServiceClient) Redirect(ctx context.Context, in *RedirectRequest, opts ...grpc.CallOption) (*RedirectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedirectResponse)
	err := c.cc.Invoke(ctx, LinkShortenerService_Redirect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkShortenerServiceServer is the server API for LinkShortenerService service.
// All implementations must embed UnimplementedLinkShortenerServiceServer
// for forward compatibility.
type LinkShortenerServiceServer interface {
	CreateLink(context.Context, *CreateLinkRequest) (*Link, error)
	GetLink(context.Context, *GetLinkRequest) (*Link, error)
	UpdateLink(context.Context, *PutLinkRequest) (*PutLinkResponse, error)
	ExtendLifeTime(context.Context, *PatchLinkRequest) (*PatchLinkResponse, error)
	DeleteMyItem(context.Context, *DeleteLinkRequest) (*DeleteLinkResponse, error)
	Redirect(context.Context, *RedirectRequest) (*RedirectResponse, error)
	mustEmbedUnimplementedLinkShortenerServiceServer()
}

// UnimplementedLinkShortenerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLinkShortenerServiceServer struct{}

func (UnimplementedLinkShortenerServiceServer) CreateLink(context.Context, *CreateLinkRequest) (*Link, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLink not implemented")
}
func (UnimplementedLinkShortenerServiceServer) GetLink(context.Context, *GetLinkRequest) (*Link, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLink not implemented")
}
func (UnimplementedLinkShortenerServiceServer) UpdateLink(context.Context, *PutLinkRequest) (*PutLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLink not implemented")
}
func (UnimplementedLinkShortenerServiceServer) ExtendLifeTime(context.Context, *PatchLinkRequest) (*PatchLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendLifeTime not implemented")
}
func (UnimplementedLinkShortenerServiceServer) DeleteMyItem(context.Context, *DeleteLinkRequest) (*DeleteLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMyItem not implemented")
}
func (UnimplementedLinkShortenerServiceServer) Redirect(context.Context, *RedirectRequest) (*RedirectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Redirect not implemented")
}
func (UnimplementedLinkShortenerServiceServer) mustEmbedUnimplementedLinkShortenerServiceServer() {}
func (UnimplementedLinkShortenerServiceServer) testEmbeddedByValue()                              {}

// UnsafeLinkShortenerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkShortenerServiceServer will
// result in compilation errors.
type UnsafeLinkShortenerServiceServer interface {
	mustEmbedUnimplementedLinkShortenerServiceServer()
}

func RegisterLinkShortenerServiceServer(s grpc.ServiceRegistrar, srv LinkShortenerServiceServer) {
	// If the following call pancis, it indicates UnimplementedLinkShortenerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LinkShortenerService_ServiceDesc, srv)
}

func _LinkShortenerService_CreateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServiceServer).CreateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkShortenerService_CreateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServiceServer).CreateLink(ctx, req.(*CreateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkShortenerService_GetLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServiceServer).GetLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkShortenerService_GetLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServiceServer).GetLink(ctx, req.(*GetLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkShortenerService_UpdateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServiceServer).UpdateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkShortenerService_UpdateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServiceServer).UpdateLink(ctx, req.(*PutLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkShortenerService_ExtendLifeTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServiceServer).ExtendLifeTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkShortenerService_ExtendLifeTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServiceServer).ExtendLifeTime(ctx, req.(*PatchLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkShortenerService_DeleteMyItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServiceServer).DeleteMyItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkShortenerService_DeleteMyItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServiceServer).DeleteMyItem(ctx, req.(*DeleteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkShortenerService_Redirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServiceServer).Redirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkShortenerService_Redirect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServiceServer).Redirect(ctx, req.(*RedirectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkShortenerService_ServiceDesc is the grpc.ServiceDesc for LinkShortenerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkShortenerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linkshortener.api.v1.LinkShortenerService",
	HandlerType: (*LinkShortenerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLink",
			Handler:    _LinkShortenerService_CreateLink_Handler,
		},
		{
			MethodName: "GetLink",
			Handler:    _LinkShortenerService_GetLink_Handler,
		},
		{
			MethodName: "UpdateLink",
			Handler:    _LinkShortenerService_UpdateLink_Handler,
		},
		{
			MethodName: "ExtendLifeTime",
			Handler:    _LinkShortenerService_ExtendLifeTime_Handler,
		},
		{
			MethodName: "DeleteMyItem",
			Handler:    _LinkShortenerService_DeleteMyItem_Handler,
		},
		{
			MethodName: "Redirect",
			Handler:    _LinkShortenerService_Redirect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/link.proto",
}
