syntax = "proto3";
package linkshortener.api.v1;

option go_package = "github.com/LittleLe6owski/link-shortener/pkg/api/v1";

import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/descriptor.proto";
import "validate/validate.proto";

service LinkShortenerService {
    rpc CreateLink(CreateLinkRequest) returns (Link) {
        option (google.api.http) = {
            post: "/api/v1/link"   
            body: "*"   
        };  
    };

    rpc GetLink(GetLinkRequest) returns (Link) {
        option (google.api.http) = {
            get: "/api/v1/link/{id}"    
        }; 
    };

    rpc UpdateLink(PutLinkRequest) returns (PutLinkResponse) {
        option (google.api.http) = {
            put: "/api/v1/link/{id}"  
            body: "*"  
        }; 
    };

    rpc ExtendLifeTime(PatchLinkRequest) returns (PatchLinkResponse) {
        option (google.api.http) = {
            patch: "/api/v1/link/{id}"  
            body: "*"  
        }; 
    };

    rpc DeleteMyItem(DeleteLinkRequest) returns (google.protobuf.Empty) {
        option (google.api.http) = {
            delete: "/api/v1/link/{id}"    
        }; 
    };
}

// Описание элемента
message Link {
    // уникальный идентификатор в формате UUID
    string id = 1;
    // полный uri
    string full_uri = 2;
    // укороченный uri
    string short_uri = 3;
    // время создания элемента
    google.protobuf.Timestamp created_at = 4;
    // время последнего изменения элемента
    google.protobuf.Timestamp updated_at = 5;
}

// Запрос на создание элемента
message CreateLinkRequest {
    // имя элемента
    string full_uri = 1 [(validate.rules).string.uri = true];
    // кол-во дней, после которого ссылка будет удалена
    optional google.protobuf.Timestamp expires_at = 2 [(validate.rules).timestamp.required = true];
}

// Запрос на получение элемента
message GetLinkRequest {
    // уникальный идентификатор в формате UUID
    string id = 1 [(validate.rules).string.uuid = true];
}

// Запрос на удаление элемента
message DeleteLinkRequest {
    // уникальный идентификатор в формате UUID
    string id = 1 [(validate.rules).string.uuid = true];
}

message PatchLinkRequest {
    // ид ссылки
    string id = 1 [(validate.rules).string.uuid = true];
    // новое время жизни в днях
    google.protobuf.Timestamp new_expires_at = 2 [(validate.rules).timestamp.required = true];
}

message PatchLinkResponse {
    // успешно ли обновили новое время жизни
    bool is_successfully = 1;
}

message PutLinkRequest {
    // ид ссылки
    string id = 1 [(validate.rules).string.uuid = true];
    // новый полный uri
    string full_uri = 2 [(validate.rules).string.uri = true];
    // новое время жизни в днях
    google.protobuf.Timestamp new_expires_at = 3 [(validate.rules).timestamp.required = true];
}

message PutLinkResponse {
    // успешно ли обновили
    bool is_successfully = 1;
}